// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: proto/addTwoNumbers/addTwoNumbers.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddTwoNumbersClient is the client API for AddTwoNumbers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddTwoNumbersClient interface {
	AddTwoNumbers(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListSum, error)
}

type addTwoNumbersClient struct {
	cc grpc.ClientConnInterface
}

func NewAddTwoNumbersClient(cc grpc.ClientConnInterface) AddTwoNumbersClient {
	return &addTwoNumbersClient{cc}
}

func (c *addTwoNumbersClient) AddTwoNumbers(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListSum, error) {
	out := new(ListSum)
	err := c.cc.Invoke(ctx, "/AddTwoNumbers/AddTwoNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddTwoNumbersServer is the server API for AddTwoNumbers service.
// All implementations must embed UnimplementedAddTwoNumbersServer
// for forward compatibility
type AddTwoNumbersServer interface {
	AddTwoNumbers(context.Context, *ListReq) (*ListSum, error)
	mustEmbedUnimplementedAddTwoNumbersServer()
}

// UnimplementedAddTwoNumbersServer must be embedded to have forward compatible implementations.
type UnimplementedAddTwoNumbersServer struct {
}

func (UnimplementedAddTwoNumbersServer) AddTwoNumbers(context.Context, *ListReq) (*ListSum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTwoNumbers not implemented")
}
func (UnimplementedAddTwoNumbersServer) mustEmbedUnimplementedAddTwoNumbersServer() {}

// UnsafeAddTwoNumbersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddTwoNumbersServer will
// result in compilation errors.
type UnsafeAddTwoNumbersServer interface {
	mustEmbedUnimplementedAddTwoNumbersServer()
}

func RegisterAddTwoNumbersServer(s grpc.ServiceRegistrar, srv AddTwoNumbersServer) {
	s.RegisterService(&AddTwoNumbers_ServiceDesc, srv)
}

func _AddTwoNumbers_AddTwoNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddTwoNumbersServer).AddTwoNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AddTwoNumbers/AddTwoNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddTwoNumbersServer).AddTwoNumbers(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AddTwoNumbers_ServiceDesc is the grpc.ServiceDesc for AddTwoNumbers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddTwoNumbers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AddTwoNumbers",
	HandlerType: (*AddTwoNumbersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTwoNumbers",
			Handler:    _AddTwoNumbers_AddTwoNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/addTwoNumbers/addTwoNumbers.proto",
}
