// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/reverseLinkedlist/reverseLinkedlist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReverseLinkedListClient is the client API for ReverseLinkedList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseLinkedListClient interface {
	ReverseLinkedList(ctx context.Context, in *LinkedList, opts ...grpc.CallOption) (*ReverseList, error)
}

type reverseLinkedListClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseLinkedListClient(cc grpc.ClientConnInterface) ReverseLinkedListClient {
	return &reverseLinkedListClient{cc}
}

func (c *reverseLinkedListClient) ReverseLinkedList(ctx context.Context, in *LinkedList, opts ...grpc.CallOption) (*ReverseList, error) {
	out := new(ReverseList)
	err := c.cc.Invoke(ctx, "/ReverseLinkedList/ReverseLinkedList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverseLinkedListServer is the server API for ReverseLinkedList service.
// All implementations must embed UnimplementedReverseLinkedListServer
// for forward compatibility
type ReverseLinkedListServer interface {
	ReverseLinkedList(context.Context, *LinkedList) (*ReverseList, error)
	mustEmbedUnimplementedReverseLinkedListServer()
}

// UnimplementedReverseLinkedListServer must be embedded to have forward compatible implementations.
type UnimplementedReverseLinkedListServer struct {
}

func (UnimplementedReverseLinkedListServer) ReverseLinkedList(context.Context, *LinkedList) (*ReverseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseLinkedList not implemented")
}
func (UnimplementedReverseLinkedListServer) mustEmbedUnimplementedReverseLinkedListServer() {}

// UnsafeReverseLinkedListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseLinkedListServer will
// result in compilation errors.
type UnsafeReverseLinkedListServer interface {
	mustEmbedUnimplementedReverseLinkedListServer()
}

func RegisterReverseLinkedListServer(s grpc.ServiceRegistrar, srv ReverseLinkedListServer) {
	s.RegisterService(&ReverseLinkedList_ServiceDesc, srv)
}

func _ReverseLinkedList_ReverseLinkedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkedList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseLinkedListServer).ReverseLinkedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReverseLinkedList/ReverseLinkedList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseLinkedListServer).ReverseLinkedList(ctx, req.(*LinkedList))
	}
	return interceptor(ctx, in, info, handler)
}

// ReverseLinkedList_ServiceDesc is the grpc.ServiceDesc for ReverseLinkedList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverseLinkedList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReverseLinkedList",
	HandlerType: (*ReverseLinkedListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReverseLinkedList",
			Handler:    _ReverseLinkedList_ReverseLinkedList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reverseLinkedlist/reverseLinkedlist.proto",
}
